### ISSUE TITLE
ReferenceError: program is not defined

### ISSUE THREAD

**Issue by pudgereyem** [eggplanetio/mert#1]
When running `mert init` it fails when referencing variable `program`. See below.

`Creating new mertrc file ${ (program.init === 'global') ? 'in home dir' : '' }`

ReferenceError: program is not defined

**Comment by AaronHolbrook** [comment]
same

**Comment by briangonzalez** [comment]
Thanks for the report. 0.3.0 pushed and published to npm.

🍻
