### ISSUE TITLE
Commands executed in wrong panel

### ISSUE THREAD

**Issue by david-zacharias** [eggplanetio/mert#13]
First of all: I really like the idea of mert!

Unfortunately, on my system when starting mert the commands get executed in the wrong panels. The attached gif shows best what happens:

![mert](https://cloud.githubusercontent.com/assets/1903179/16145158/a215a6c2-3477-11e6-80ed-c050d3392a2b.gif)
- iTerm 2 Build 3.0.2
- Node v6.2.0
- OS X 10.11.5 (15F34)

Maybe it's just settings in iTerm? Help and hints appreciated.

**Comment by briangonzalez** [comment]
Trying this myself. I'll report back with findings.

**Comment by briangonzalez** [comment]
![screen capture on 2016-06-17 at 21-04-15 1](https://cloud.githubusercontent.com/assets/659829/16168932/48bf9d32-34cf-11e6-9f49-cdbcfa616aec.gif)

**Comment by briangonzalez** [comment]
@david-zacharias You wouldn't happen to have custom keyboard mappings, would you?

**Comment by juancaldera** [comment]
@david-zacharias does this happen consistently?

**Comment by david-zacharias** [comment]
Hi all, sorry for my delayed feedback.

@juancaldera: Yes, it happens consistently.

@briangonzalez: No, no extra shortcuts defined.

I took a look into the code and I think I know what's causing my issue: The `NEXTPANE` and `PREVPANE` commands do not work on machines with with German keyboard layout (see also [comments](http://stackoverflow.com/questions/9246235/iterm2-keyboard-shortcut-split-pane-navigation)) cause there are no dedicated keys for `[` and `]`. These are created by <kbd>ALT</kbd>+<kbd>5</kbd> and <kbd>ALT</kbd>+<kbd>6</kbd> respectively. 

From some reading I think that ~~CMD + _Arrow Keys_~~ <kbd>CMD</kbd> + <kbd>⌥</kbd> + _Arrow Keys_  work on any keyboard layout. But since they operate in four directions the code would need some extra logic to apply these correctly. 

Other idea: How about making the `commands` configurable via global config?

**Comment by michaelmoussa** [comment]
@david-zacharias <kbd>CMD</kbd> + <kbd>OPTION</kbd> + _Arrows_ works on my US standard keyboard - does that work on your German keyboard layout?

I think switching from the current configured hotkeys to the above convention (plus allowing global override for any edge cases) would be the best approach here.

**Comment by david-zacharias** [comment]
Yes, <kbd>⌘</kbd> + <kbd>⌥</kbd> + _Arrows_ works on German standard layout. I have missed the <kbd>OPTION</kbd>-Key in the list in my previous comment.

So from my point of view changing to this shortcuts would increase compatibility.

**Comment by michaelmoussa** [comment]
@briangonzalez I tried it out this evening and it seems it won't be as simple as just switching to <kbd>CMD</kbd> + <kbd>OPTION</kbd> + _Arrows_. <kbd>CMD</kbd> + <kbd>[</kbd> and <kbd>CMD</kbd> + <kbd>]</kbd> are for "next pane" and "previous pane", while <kbd>CMD</kbd> + <kbd>OPTION</kbd> + _Arrows_ select the pane in the direction of the arrow.

So, the arrow-based command isn't a drop-in replacement - there'd need to be some tweaking to the code that builds the layout in order for it to be able to work by moving focus in certain directions rather than just next/previous.

Don't know if you might have a better approach in mind...

**Comment by briangonzalez** [comment]
@juancaldera and I took a stab at this last night. It's at this PR: https://github.com/eggplanetio/mert/pull/14

We're invoking the applescript API directly – no more keystrokes!

**Comment by briangonzalez** [comment]
Closed via https://github.com/eggplanetio/mert/pull/14
