### ISSUE TITLE
Ability to specify what pane has the focus

### ISSUE THREAD

**Issue by apsoto** [eggplanetio/mert#16]
When opening multiple panes, the first pane always has the focus.  In my particular use case, I'd like the last pane to have the focus, but hopefully it can be generalized to allow me to specify which pane should have the focus.

**Comment by briangonzalez** [comment]
@apsoto Do you know if iTerm has an applescript API for focusing panes?

**Comment by apsoto** [comment]
I've never used their Applescript API, but looking here (https://www.iterm2.com/documentation-scripting.html) I don't see anything specifying Panes and Focus.  However,  I do see the `select` keyword mentioned for Windows and Tabs.  Maybe it's undocumented and possibly works with Panes too.
