### ISSUE TITLE
capitalization is strange with iterm2 3.0.14

### ISSUE THREAD

**Issue by paultopia** [eggplanetio/mert#25]
Very odd behavior.  I have a project with the following .mertrc

```
layout:
  -
    - mongod
    - sleep 1 && lein run
  -
    - sleep 60 && lein figwheel
  -
    - sleep 60 && lein repl :connect 7000 
```

when I run "mert start," however, 3/4 of the commands get capitalized wrong.  I get:

> sleep 1 && Lein RUn

> sleep 60 && LeIN figwheel

> sleep 60 && LEIN repl :connect 7000

Which is an issue, because some of these commands are case-sensitive...

It looks like the cd commands that mert executes to get into the working directory from the new terminal windows also have wonky capitalization.

I've double-checked that I'm running the latest version of mert by running `npm update -g mert`  I'm also running node v6.2.1 and iterm 3.0.14

**Comment by briangonzalez** [comment]
@paultopia Does it happen consistently?

**Comment by paultopia** [comment]
Yes.  One possible confound is that I just copied the .mertrc file from another project rather than creating it with the init functionality.  But in the new project it's happened every time I've run it.

**Comment by briangonzalez** [comment]
Any chance you could upload the file somewhere? I'll try to reproduce.

**Comment by paultopia** [comment]
Actually, because I'm lazy with my .gitignore, it's already in a repo here!  :-) [This is the project](https://github.com/paultopia/toscoding) causing the problem, complete with .mertrc.
