### ISSUE TITLE
Launch panes in new tab rather than new window?

### ISSUE THREAD

**Issue by michaelmoussa** [eggplanetio/mert#8]
My iTerm setup is full-screen with no borders / hidden menu / etc, and I prefer to have a _single_ window with multiple tabs, and those tabs containing panes in my preferred splits. Is there any way to have mert start in a new tab rather than opening up a new window for every session?

**Comment by briangonzalez** [comment]
@michaelmoussa #5 outlines how we're going to achieve this, let's track the issue there.

**Comment by michaelmoussa** [comment]
Thanks @briangonzalez . Will add thoughts there.

**Comment by briangonzalez** [comment]
Going to do work here: https://github.com/eggplanetio/mert/pull/9
